version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: whitebox_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - common-network

  rabbitmq:
    image: rabbitmq:3.9.22-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - common-network

  java-monitor-service:
    image: java-monitor-service
    container_name: java-monitor-service
    build:
      context: ./java-monitor-service
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
      - rabbitmq
    restart: always
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/whitebox_db?useSSL=false&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - common-network

  notification-service:
    image: notification-service
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - "8090:8090"
    networks:
      - common-network
networks:
  common-network:
    driver: bridge

volumes:
  db_data:
    driver: local


